apiVersion: v1
kind: Service
metadata:
  name: api-images
  labels:
    app: api-images
    istio-metrics: 'true'
  namespace: api
spec:
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: http
  - port: 15020
    targetPort: 15020
    protocol: TCP
    name: http-metrics
  type: ClusterIP
  selector:
    app: api-images